import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";
const API="http://localhost:8080/api/students";
function App(){const[students,setStudents]=useState([]),[editingId,setEditingId]=useState(null),[message,setMessage]=useState(""),[form,setForm]=useState({name:"",email:"",phone:"",department:"",year:""});
const load=async()=>{try{const r=await fetch(API);if(!r.ok)throw 0;setStudents(await r.json())}catch{setMessage("⚠ Unable to connect to Spring Boot backend.")}};useEffect(()=>{load()},[]);
const change=e=>setForm({...form,[e.target.name]:e.target.value});const reset=()=>{setEditingId(null);setForm({name:"",email:"",phone:"",department:"",year:""})};
const submit=async e=>{e.preventDefault();try{const r=await fetch(editingId?`${API}/${editingId}`:API,{method:editingId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,year:Number(form.year)})});if(!r.ok)throw 0;setMessage(editingId?"✓ Student updated successfully!":"✓ Student added successfully!");reset();load()}catch{setMessage("⚠ Request failed. Check backend and CORS.")}};
const edit=s=>{setEditingId(s.id);setForm({name:s.name||"",email:s.email||"",phone:s.phone||"",department:s.department||"",year:s.year||""});setMessage(`✎ Editing ${s.name||"student"} (ID: ${s.id})`);scrollTo({top:0,behavior:"smooth"})};
const del=async id=>{if(!confirm("Are you sure you want to delete this student?"))return;try{const r=await fetch(`${API}/${id}`,{method:"DELETE"});if(!r.ok)throw 0;setMessage("✓ Student deleted successfully!");load()}catch{setMessage("⚠ Could not delete the student.")}};
return <div className="app"><header className="hero"><div className="badge">STUDENT PORTAL</div><h1>Student Management System</h1><p>Manage student records quickly, simply and efficiently.</p><div className="stats"><div><b>{students.length}</b><span>Total Students</span></div><div><b>CRUD</b><span>Full Management</span></div><div><b>24/7</b><span>Digital Access</span></div></div></header>
<main className="container"><section className="card"><span className="tag">{editingId?"UPDATE MODE":"NEW RECORD"}</span><h2>{editingId?"Update Student":"Add New Student"}</h2><p className="desc">Enter the student information below.</p><form onSubmit={submit}>
<label>Full Name<input name="name" placeholder="Enter student name" value={form.name} onChange={change} required/></label>
<label>Email Address<input name="email" type="email" placeholder="Enter email address" value={form.email} onChange={change} required/></label>
<label>Phone Number<input name="phone" placeholder="Enter phone number" value={form.phone} onChange={change} required/></label>
<label>Department<input name="department" placeholder="Example: CSE" value={form.department} onChange={change} required/></label>
<label>Year<input name="year" type="number" min="1" placeholder="Enter year" value={form.year} onChange={change} required/></label>
<div className="formactions"><button className="primary">{editingId?"Save Changes":"Add Student"}</button>{editingId&&<button className="secondary" type="button" onClick={reset}>Cancel</button>}</div></form>{message&&<div className="message">{message}</div>}</section>
<section className="card"><div className="listhead"><div><span className="tag">DATABASE RECORDS</span><h2>Students Directory</h2><p className="desc">View, update and manage all student information.</p></div><button className="secondary" onClick={load}>↻ Refresh</button></div>
{students.length===0?<div className="empty"><div>🎓</div><h3>No students found</h3><p>Add your first student using the form above.</p></div>:<div className="tablewrap"><table><thead><tr><th>ID</th><th>Student</th><th>Email</th><th>Phone</th><th>Department</th><th>Year</th><th>Actions</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td><i>#{s.id}</i></td><td className="name">{s.name}</td><td>{s.email}</td><td>{s.phone}</td><td><em>{s.department}</em></td><td>{s.year}</td><td><button className="edit" onClick={()=>edit(s)}>Edit</button><button className="delete" onClick={()=>del(s.id)}>Delete</button></td></tr>)}</tbody></table></div>}</section></main>
<footer><div></div><p>Created with ❤️ by <strong>Dharun K K</strong></p><span>Student Management System • Spring Boot • PostgreSQL • React</span></footer></div>}
createRoot(document.getElementById("root")).render(<App/>);